name: webview
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  path_provider: ^2.1.5
  webview_flutter_android: ^4.3.1
  webview_flutter_wkwebview: ^3.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
